# from https://gitlab.multimedia.hs-augsburg.de/kowa/wk_account_postgres_01

version: "3"

services:
    postgres_db:
        container_name: "postgres_db_webprog"
        build:
            context: ./postgres
            args:
                WEB_DB: ${WEB_DB}
        ports:
            - 5432:5432
    
    adminer:
        container_name: "adminer_postgres_webprog"
        build:
            context: ./adminer
        ports:
            - 11000:8080
